# API documentation:
# https://github.com/NatLibFi/Skosmos/wiki/REST-API
term:
#  url:                http://aims.fao.org/skosmos/rest/v1/data?uri=__TERM_ID__
  url:                http://aims.fao.org/skosmos/rest/v1/data?uri=http://aims.fao.org/aos/agrovoc/__TERM_ID__
  http_accept:        application/rdf+xml
  term_id:            ID                    # valid values:  ID | URI
  language:           en
  results:
    label_predicate:    http://www.w3.org/2004/02/skos/core#prefLabel
    altlabel_predicate: http://www.w3.org/2004/02/skos/core#altLabel
    broader_predicate:  http://www.w3.org/2004/02/skos/core#broader
    narrower_predicate: http://www.w3.org/2004/02/skos/core#narrower
    sameas_predicate:   http://www.w3.org/2004/02/skos/core#exactMatch
search:
  url:                http://aims.fao.org/skosmos/rest/v1/search/?query=*__QUERY__*&lang=__LANG__
  http_accept:        application/json
  replacement_count:  1
  replacement_1:
    param:    lang
    pattern:  __LANG__
    default:  "en"
  results:
    label_predicate:    http://www.w3.org/2004/02/skos/core#prefLabel
    altlabel_predicate: http://www.w3.org/2004/02/skos/core#altLabel
